spring:
  cloud:
    nacos:
      discovery:
        register-enabled: false

workbench:
  demo-admin:
    enabled: true
    storage-swap-mode: COPY_VERIFY

logging:
  level:
    com.hsmap.factverification: INFO
